server:
  port: 7008
spring:
  application:
    name: MhSysManager
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    #driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.1.103:3306/mhshopdb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.103:8848
  security:
    oauth2:
      client:
        client-id: password
        client-secrect: 123

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.meihong.entity   # 所有Entity别名类所在包# pagehelper
# pagehelper
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0